# Lecture 2

## Topic 1> 시계열 데이터 변환

###   시계열 --> 지도학습용 2D 데이터

In [ ]:
# 기본적으로 8개 -> (일변량 or 다변량) x (일변량 or 다변량) x 예측구간(하루 or 하루이상)
# 데이터를 목적에 맞게 변환하는 방법학습
# 패키지에서 필요한거만 불러오면 -> 메모리x / 네이밍 

In [1]:
# univariate time series -> supervised learning problem 
# 일변량 1기간 예측
from numpy import array

# split a univariate sequence into samples 
# ex) x1, x2, x3, y
#      1,  2,  3, 4
def split_sequence(sequence, n_steps): #sequence: 데이터 n_steps: 구간
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y)
    return array(X), array(y)

In [11]:
# define univariate time series 
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
print('series.shape:',series.shape)
print ('-------------------------')

# transform to a supervised learning problem 
X, y = split_sequence(series, 3) 
print('X.shape, y.shape:',X.shape, y.shape) 
print ('-------------------------')
# show each sample 
for i in range(len(X)): 
    print('X[i] | y[i]:',X[i],'|', y[i])

series.shape: (10,)
-------------------------
X.shape, y.shape: (7, 3) (7,)
-------------------------
X[i] | y[i]: [1 2 3] | 4
X[i] | y[i]: [2 3 4] | 5
X[i] | y[i]: [3 4 5] | 6
X[i] | y[i]: [4 5 6] | 7
X[i] | y[i]: [5 6 7] | 8
X[i] | y[i]: [6 7 8] | 9
X[i] | y[i]: [7 8 9] | 10


### 2D 데이터 --> 3D 데이터

In [18]:
# transform univariate 2d to 3d 
# 일변량 1기간 예측
from numpy import array

# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [20]:
# define univariate time series 
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
print('series.shape:',series.shape) 
print ('-------------------------')
# transform to a supervised learning problem 
X, y = split_sequence(series, 3) 
print('X.shape | y.shape:',X.shape,'|', y.shape) 
print ('-------------------------')
# transform input from [samples, features] to [samples, timesteps, features] 
X = X.reshape((X.shape[0], X.shape[1], 1)) #2d -> 3d로 변환
print('X.shape:', X.shape)

series.shape: (10,)
-------------------------
X.shape | y.shape: (7, 3) | (7,)
-------------------------
X.shape: (7, 3, 1)


### 적용 사례

In [27]:
# load time series dataset
import pandas as pd
location = "/Users/hankiho/Downloads/Python으로 배우는 딥러닝 시계열 예측(고급)/Week_01/AdvancedDeepLearningTSF/Data/Sales.csv" 
series = pd.read_csv(location, header=0)

# numpy array로 전환
import numpy as np
data = np.array(series)
print(data[:5, :])
print ('-------------------------')
print('data.shape:',data.shape)

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
-------------------------
data.shape: (5000, 2)


In [28]:
# drop time 
data = data[:, 1] 
print('data.shape:',data.shape)

data.shape: (5000,)


In [29]:
# split into samples (e.g. 5000/200 = 25) 
n = len(data)
samples = list() 
length = 200 
# step over the 5,000 in jumps of 200 
for i in range(0,n,length): 
    # grab from i to i + 200 
    sample = data[i:i+length] 
    samples.append(sample) 
print('len:',len(samples))

len: 25


In [30]:
# convert list of arrays into 3d array 
data = array(samples) 
# reshape into [samples, timesteps, features] 
data = data.reshape((len(samples), length, 1)) 
print('data.shape:',data.shape)

data.shape: (25, 200, 1)


In [20]:
data[0,:,:]

array([[  10],
       [  20],
       [  30],
       [  40],
       [  50],
       [  60],
       [  70],
       [  80],
       [  90],
       [ 100],
       [ 110],
       [ 120],
       [ 130],
       [ 140],
       [ 150],
       [ 160],
       [ 170],
       [ 180],
       [ 190],
       [ 200],
       [ 210],
       [ 220],
       [ 230],
       [ 240],
       [ 250],
       [ 260],
       [ 270],
       [ 280],
       [ 290],
       [ 300],
       [ 310],
       [ 320],
       [ 330],
       [ 340],
       [ 350],
       [ 360],
       [ 370],
       [ 380],
       [ 390],
       [ 400],
       [ 410],
       [ 420],
       [ 430],
       [ 440],
       [ 450],
       [ 460],
       [ 470],
       [ 480],
       [ 490],
       [ 500],
       [ 510],
       [ 520],
       [ 530],
       [ 540],
       [ 550],
       [ 560],
       [ 570],
       [ 580],
       [ 590],
       [ 600],
       [ 610],
       [ 620],
       [ 630],
       [ 640],
       [ 650],
       [ 660],
       [ 6

## Topic 2> MLP 시계열 모형

### Univariate MLP Model

In [35]:
# univariate mlp example
# 복잡하지않는 시계열 데이터에 적합하다.
# MLP는 3차원으로 전환할 필요가 없다.
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

Using TensorFlow backend.


In [45]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3

# split into samples
X, y = split_sequence(raw_seq, n_steps)
# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=2000, verbose=0) # verbose=0 학습 결과가 안나오게함

# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps))
yhat = model.predict(x_input, verbose=0)

print('yhat:',yhat) # 시드가 고정이 안되있어서 값이 계속 바뀜.

yhat: [[101.99584]]


### Multivariate MLP Modles

#### Multiple Input Series

In [ ]:
# Multiple Input Series: 둘 이상의 병렬적 입력 시계열과 하나의 출력 시계열로 구성
# (출력 시계열은 입력 시계열과 연관되어 있음)

In [47]:
# multivariate mlp example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense

In [48]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [49]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

In [4]:
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [56]:
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)

In [57]:
print(X.shape, y.shape)

(7, 3, 2) (7,)


In [60]:
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [61]:
# flatten input: 여러개의 백터를 한 백터로 나타내준다.
n_input = X.shape[1] * X.shape[2] #백터의 길이
X = X.reshape((X.shape[0], n_input))

In [62]:
print(X)

[[10 15 20 25 30 35]
 [20 25 30 35 40 45]
 [30 35 40 45 50 55]
 [40 45 50 55 60 65]
 [50 55 60 65 70 75]
 [60 65 70 75 80 85]
 [70 75 80 85 90 95]]


In [63]:
# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_input))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [64]:
# fit model
model.fit(X, y, epochs=2000, verbose=0)

In [65]:
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)

In [70]:
print(yhat)

[[205.82436]]


#### Multi-headed

In [ ]:
# Multi-headed: Multiple Input Series를 개선시킨 모델. (개별로 처리)

In [71]:
# multivariate mlp example
from numpy import array
from numpy import hstack
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers.merge import concatenate

In [72]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [73]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)

In [74]:
# separate input data
X1 = X[:, :, 0]
X2 = X[:, :, 1]

In [81]:
# first input model
visible1 = Input(shape=(n_steps,))
dense1 = Dense(100, activation='relu')(visible1)

# second input model
visible2 = Input(shape=(n_steps,))
dense2 = Dense(100, activation='relu')(visible2)

# merge input models
merge = concatenate([dense1, dense2])
output = Dense(1)(merge)
model = Model(inputs=[visible1, visible2], outputs=output)
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit([X1, X2], y, epochs=2000, verbose=0)

In [90]:
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x1 = x_input[:, 0].reshape((1, n_steps))
x2 = x_input[:, 1].reshape((1, n_steps))
yhat = model.predict([x1, x2], verbose=0)
print(yhat)

[[205.41597]]


#### Multiple Pararell Series

In [100]:
# Multiple Parallel Series: 다수의 병렬적시계열이 존재하고 각 시계열에 대해값을 예측

In [1]:
# multivariate output mlp example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import Dense

Using TensorFlow backend.


In [91]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the dataset 
        if end_ix > len(sequences)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :] # 이 부분이 다름
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [92]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps = 3 
# convert into input/output 
X, y = split_sequences(dataset, n_steps) 

In [93]:
print(X.shape, y.shape) 

(6, 3, 3) (6, 3)


In [94]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [95]:
# flatten input 
n_input = X.shape[1] * X.shape[2] 
X = X.reshape((X.shape[0], n_input)) 
n_output = y.shape[1] 

In [96]:
print(X.shape, y.shape) 

(6, 9) (6, 3)


In [97]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

[10 15 25 20 25 45 30 35 65] [40 45 85]
[20 25 45 30 35 65 40 45 85] [ 50  55 105]
[ 30  35  65  40  45  85  50  55 105] [ 60  65 125]
[ 40  45  85  50  55 105  60  65 125] [ 70  75 145]
[ 50  55 105  60  65 125  70  75 145] [ 80  85 165]
[ 60  65 125  70  75 145  80  85 165] [ 90  95 185]


In [98]:
# define model 
model = Sequential() 
model.add(Dense(100, activation='relu', input_dim=n_input)) 
model.add(Dense(n_output)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=2000, verbose=0) 
# demonstrate prediction 
x_input = array([[70,75,145], [80,85,165], [90,95,185]]) 
x_input = x_input.reshape((1, n_input)) 
yhat = model.predict(x_input, verbose=0) 

In [99]:
print(yhat)

[[101.07385 106.40147 206.32042]]


#### Multi-output

In [ ]:
#Multi-output: 개별적으로 MLP 출력 모형을 만들어 각 출력 시계열을 처리함

In [12]:
# multivariate output mlp example 
from numpy import array 
from numpy import hstack 
from keras.models import Model 
from keras.layers import Input 
from keras.layers import Dense

In [103]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the dataset 
        if end_ix > len(sequences)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps = 3 
# convert into input/output 
X, y = split_sequences(dataset, n_steps) 
# flatten input 
n_input = X.shape[1] * X.shape[2]
X = X.reshape((X.shape[0], n_input))

In [104]:
# separate output 
y1 = y[:, 0].reshape((y.shape[0], 1)) 
y2 = y[:, 1].reshape((y.shape[0], 1)) 
y3 = y[:, 2].reshape((y.shape[0], 1)) 

In [105]:
# define model 
visible = Input(shape=(n_input,)) 
dense = Dense(100, activation='relu')(visible) 

In [106]:
# define output 1 
output1 = Dense(1)(dense) 
# define output 2 
output2 = Dense(1)(dense) 
# define output 3
output3 = Dense(1)(dense) 

In [107]:
# tie together 
model = Model(inputs=visible, outputs=[output1, output2, output3])
model.compile(optimizer='adam', loss='mse') 

In [108]:
# fit model 
model.fit(X, [y1,y2,y3], epochs=2000, verbose=0) 

In [109]:
# demonstrate prediction 
x_input = array([[70,75,145], [80,85,165], [90,95,185]]) 
x_input = x_input.reshape((1, n_input)) 
yhat = model.predict(x_input, verbose=0) 

In [110]:
print(yhat)
# 개별 개별이라 array형태로 나오는 것이다.

[array([[100.69115]], dtype=float32), array([[107.55654]], dtype=float32), array([[207.86743]], dtype=float32)]


### Multi-step MLP Models

In [ ]:
# Multi-step MLP Models: 다기간 예측

In [21]:
# univariate multi-step vector-output mlp example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import Dense

In [111]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the sequence 
        if out_end_ix > len(sequence): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [112]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# split into samples 
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out) 

In [117]:
# define model 
model = Sequential() 
model.add(Dense(100, activation='relu', input_dim=n_steps_in)) 
model.add(Dense(n_steps_out)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=2000, verbose=0) 
# demonstrate prediction 
x_input = array([70, 80, 90]) 
x_input = x_input.reshape((1, n_steps_in)) 
yhat = model.predict(x_input, verbose=0)

In [118]:
print(yhat)

[[102.51365 114.10563]]


### Multivariate Multi-step MLP Models

#### Multiple Input Multi-step Output

In [ ]:
# Multiple Input Multi-output: 

In [1]:
# multivariate multi-step data preparation
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [119]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out-1
        # check if we are beyond the dataset
        if out_end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [120]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# choose a number of time steps
n_steps_in, n_steps_out = 3, 2

# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
print(X.shape, y.shape)

# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 2) (6, 2)
[[10 15]
 [20 25]
 [30 35]] [65 85]
[[20 25]
 [30 35]
 [40 45]] [ 85 105]
[[30 35]
 [40 45]
 [50 55]] [105 125]
[[40 45]
 [50 55]
 [60 65]] [125 145]
[[50 55]
 [60 65]
 [70 75]] [145 165]
[[60 65]
 [70 75]
 [80 85]] [165 185]


In [121]:
# flatten input
n_input = X.shape[1] * X.shape[2]
X = X.reshape((X.shape[0], n_input))

# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_input))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=2000, verbose=0)

# demonstrate prediction
x_input = array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)

In [122]:
print(yhat)

[[186.49048 206.31746]]


#### Multiple Parallel Input Multi-step Output

In [6]:
# multivariate multi-step mlp example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense

In [7]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # check if we are beyond the dataset
        if out_end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [8]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# choose a number of time steps
n_steps_in, n_steps_out = 3, 2

# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
print('X.shape, y.shape:',X.shape, y.shape)

# summarize the data
for i in range(len(X)):
    print(X[i], y[i]) #밀렸음

(5, 3, 3) (5, 2, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [[ 40  45  85]
 [ 50  55 105]]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [[ 50  55 105]
 [ 60  65 125]]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [[ 60  65 125]
 [ 70  75 145]]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [[ 70  75 145]
 [ 80  85 165]]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [[ 80  85 165]
 [ 90  95 185]]


In [9]:
# flatten input
n_input = X.shape[1] * X.shape[2]
X = X.reshape((X.shape[0], n_input))

# flatten output
n_output = y.shape[1] * y.shape[2]
y = y.reshape((y.shape[0], n_output))

# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_input))
model.add(Dense(n_output))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=2000, verbose=0)

# demonstrate prediction
x_input = array([[60, 65, 125], [70, 75, 145], [80, 85, 165]])
x_input = x_input.reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)

In [10]:
print(yhat)

[[ 89.899185  94.788155 185.143     99.97876  104.982506 205.4795  ]]


## Topic 3 CNN 시계열 모형

### Univariate CNN

In [ ]:
# univariate cnn example
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [ ]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# choose a number of time steps
n_steps = 3

# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [ ]:
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

In [ ]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [ ]:
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# fit model
model.fit(X, y, epochs=1000, verbose=0)

In [ ]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)

In [ ]:
print(yhat)

### Multivariate CNN

#### Vector-input CNN Model 

In [ ]:
# multivariate cnn example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [ ]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [ ]:
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

In [ ]:
print(dataset)

In [ ]:
# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)

In [ ]:
print(X.shape, y.shape)

In [ ]:
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

In [ ]:
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]

# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps,
n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
# fit model
model.fit(X, y, epochs=1000, verbose=0)

In [ ]:
demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)

In [ ]:
print(yhat)

#### Multi-headed CNN Model

In [ ]:
# multivariate multi-headed 1d cnn example
from numpy import array
from numpy import hstack
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.merge import concatenate

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)

In [ ]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))

# choose a number of time steps
n_steps = 3

# convert into input/output
X, y = split_sequences(dataset, n_steps)

In [ ]:
# one time series per head
n_features = 1

# separate input data
X1 = X[:, :, 0].reshape(X.shape[0], X.shape[1], n_features)
X2 = X[:, :, 1].reshape(X.shape[0], X.shape[1], n_features)

In [ ]:
# first input model
visible1 = Input(shape=(n_steps, n_features))
cnn1 = Conv1D(filters=64, kernel_size=2, activation='relu')(visible1)
cnn1 = MaxPooling1D(pool_size=2)(cnn1)
cnn1 = Flatten()(cnn1)

# second input model
visible2 = Input(shape=(n_steps, n_features))
cnn2 = Conv1D(filters=64, kernel_size=2, activation='relu')(visible2)
cnn2 = MaxPooling1D(pool_size=2)(cnn2)
cnn2 = Flatten()(cnn2)

In [ ]:
# merge input models
merge = concatenate([cnn1, cnn2])
dense = Dense(50, activation='relu')(merge)
output = Dense(1)(dense)
model = Model(inputs=[visible1, visible2], outputs=output)
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit([X1, X2], y, epochs=1000, verbose=0)

In [ ]:
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x1 = x_input[:, 0].reshape((1, n_steps, n_features))
x2 = x_input[:, 1].reshape((1, n_steps, n_features))
yhat = model.predict([x1, x2], verbose=0)

In [ ]:
print(yhat)

#### Vector-out CNN Model

In [ ]:
# multivariate output 1d cnn example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import Flatten 
from keras.layers.convolutional import Conv1D 
from keras.layers.convolutional import MaxPooling1D

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the dataset 
        if end_ix > len(sequences)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :] 
        X.append(seq_x)
        y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 

# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 

# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 

# choose a number of time steps 
n_steps = 3 

# convert into input/output 
X, y = split_sequences(dataset, n_steps)

In [ ]:
# the dataset knows the number of features, e.g. 2 
n_features = X.shape[2] 

# define model 
model = Sequential() 
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features))) 
model.add(MaxPooling1D(pool_size=2)) 
model.add(Flatten()) 
model.add(Dense(50, activation='relu')) 
model.add(Dense(n_features)) 
model.compile(optimizer='adam', loss='mse') 

# fit model 
model.fit(X, y, epochs=3000, verbose=0) 

In [ ]:
# demonstrate prediction 
x_input = array([[70,75,145], [80,85,165], [90,95,185]]) 
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

#### Multi-output CNN Model

In [ ]:
# multivariate output 1d cnn example 
from numpy import array 
from numpy import hstack 
from keras.models import Model 
from keras.layers import Input 
from keras.layers import Dense 
from keras.layers import Flatten 
from keras.layers.convolutional import Conv1D 
from keras.layers.convolutional import MaxPooling1D

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the dataset 
        if end_ix > len(sequences)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 

# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 

# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 

# choose a number of time steps 
n_steps = 3
X, y = split_sequences(dataset, n_steps)

# the dataset knows the number of features, e.g. 2 
n_features = X.shape[2] 

In [ ]:
# separate output 
y1 = y[:, 0].reshape((y.shape[0], 1)) 
y2 = y[:, 1].reshape((y.shape[0], 1)) 
y3 = y[:, 2].reshape((y.shape[0], 1)) 

# define model 
visible = Input(shape=(n_steps, n_features)) 
cnn = Conv1D(filters=64, kernel_size=2, activation='relu')(visible) 
cnn = MaxPooling1D(pool_size=2)(cnn) 
cnn = Flatten()(cnn) 
cnn = Dense(50, activation='relu')(cnn) 

# define output 1 
output1 = Dense(1)(cnn) 

# define output 2 
output2 = Dense(1)(cnn) 

# define output 3 
output3 = Dense(1)(cnn) 

# tie together 
model = Model(inputs=visible, outputs=[output1, output2, output3]) 
model.compile(optimizer='adam', loss='mse') 

# fit model 
model.fit(X, [y1,y2,y3], epochs=2000, verbose=0) 

# demonstrate prediction 
x_input = array([[70,75,145], [80,85,165], [90,95,185]]) 
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0)

In [ ]:
print(yhat)

### Multi-step CNN Models(UI UO MS) 

In [ ]:
# univariate multi-step vector-output 1d cnn example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import Flatten 
from keras.layers.convolutional import Conv1D 
from keras.layers.convolutional import MaxPooling1D

In [ ]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the sequence 
        if out_end_ix > len(sequence): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# split into samples 
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out) 
# reshape from [samples, timesteps] into [samples, timesteps, features] 
n_features = 1 
X = X.reshape((X.shape[0], X.shape[1], n_features)) 

In [ ]:
# define model 
model = Sequential() 
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps_in, n_features))) 
model.add(MaxPooling1D(pool_size=2)) 
model.add(Flatten()) 
model.add(Dense(50, activation='relu')) 
model.add(Dense(n_steps_out)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=2000, verbose=0) 

In [ ]:
print(yhat)

### Multivariate Multi-step CNN Models

#### Multiple Input Multi-step Output(MI UO MS)

In [ ]:
# multivariate multi-step 1d cnn example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import Flatten 
from keras.layers.convolutional import Conv1D 
from keras.layers.convolutional import MaxPooling1D

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out-1 
        # check if we are beyond the dataset 
        if out_end_ix > len(sequences): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix, -1] 
        X.append(seq_x) y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# convert into input/output 
X, y = split_sequences(dataset, n_steps_in, n_steps_out) 
print(X.shape, y.shape) 

In [ ]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

In [ ]:
# the dataset knows the number of features, e.g. 2 
n_features = X.shape[2] 
# define model 
model = Sequential() 
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps_in, n_features))) 
model.add(MaxPooling1D(pool_size=2)) 
model.add(Flatten()) 
model.add(Dense(50, activation='relu')) 
model.add(Dense(n_steps_out)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=2000, verbose=0) 
# demonstrate prediction 
x_input = array([[70, 75], [80, 85], [90, 95]]) 
x_input = x_input.reshape((1, n_steps_in, n_features)) 
yhat = model.predict(x_input, verbose=0)

In [ ]:
print(yhat)

#### Multiple Parallel Input Multi-step Output(MI MO MS)

In [ ]:
# multivariate output multi-step 1d cnn example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import Flatten 
from keras.layers.convolutional import Conv1D 
from keras.layers.convolutional import MaxPooling1D

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the dataset 
        if out_end_ix > len(sequences): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :] 
        X.append(seq_x) y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# convert into input/output 
X, y = split_sequences(dataset, n_steps_in, n_steps_out) 

print(X.shape, y.shape) 

In [ ]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

In [ ]:
# flatten output 
n_output = y.shape[1] * y.shape[2] 
y = y.reshape((y.shape[0], n_output)) 
# the dataset knows the number of features, e.g. 2 
n_features = X.shape[2]
# define model 
model = Sequential() 
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps_in, n_features))) 
model.add(MaxPooling1D(pool_size=2)) 
model.add(Flatten()) 
model.add(Dense(50, activation='relu')) 
model.add(Dense(n_output)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=7000, verbose=0) 
# demonstrate prediction 
x_input = array([[60, 65, 125], [70, 75, 145], [80, 85, 165]]) 
x_input = x_input.reshape((1, n_steps_in, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

## Topic 4 LSTM 시계열 모형

### Univariate LSTM Models

#### Data Preparation

In [1]:
# univariate data preparation 
from numpy import array

In [2]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [3]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
# choose a number of time steps 
n_steps = 3 
# split into samples 
X, y = split_sequence(raw_seq, n_steps) 
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [4]:
print(X)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]


In [6]:
X.shape

(6, 3)

In [5]:
print(y)

[40 50 60 70 80 90]


In [7]:
y.shape

(6,)

#### Vanilla LSTM

In [1]:
# univariate lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 

# choose a number of time steps 
n_steps = 3 

# split into samples 
X, y = split_sequence(raw_seq, n_steps) 

In [4]:
# reshape from [samples, timesteps] into [samples, timesteps, features] 
n_features = 1 
X = X.reshape((X.shape[0], X.shape[1], n_features)) 

# define model 
model = Sequential() 
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features))) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse') 

# fit model 
model.fit(X, y, epochs=200, verbose=0) 

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [5]:
# demonstrate prediction 
x_input = array([70, 80, 90]) 
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0) 

In [6]:
print(yhat)

[[102.89083]]


#### Stacked LSTM

In [ ]:
# univariate stacked lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense

In [ ]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 

# choose a number of time steps 
n_steps = 3 

# split into samples 
X, y = split_sequence(raw_seq, n_steps)

# reshape from [samples, timesteps] into [samples, timesteps, features] 
n_features = 1 
X = X.reshape((X.shape[0], X.shape[1], n_features)) 

In [ ]:
# define model 
model = Sequential() 
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features))) 
model.add(LSTM(50, activation='relu')) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse') 

# fit model 
model.fit(X, y, epochs=200, verbose=0) 

# demonstrate prediction 
x_input = array([70, 80, 90]) 
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

#### Biderectional LSTM

In [1]:
# univariate bidirectional lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense 
from keras.layers import Bidirectional

Using TensorFlow backend.


In [2]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 

# choose a number of time steps 
n_steps = 3 

# split into samples 
X, y = split_sequence(raw_seq, n_steps)

# reshape from [samples, timesteps] into [samples, timesteps, features] 
n_features = 1 
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [3]:
# define model 
model = Sequential() 
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features))) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse')

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
# fit model 
model.fit(X, y, epochs=200, verbose=0) 
# demonstrate prediction 
x_input = array([70, 80, 90]) 
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 

Instructions for updating:
Use tf.cast instead.


In [5]:
print(yhat)

[[102.42606]]


#### CNN-LSTM

In [1]:
# univariate cnn lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense 
from keras.layers import Flatten 
from keras.layers import TimeDistributed 
from keras.layers.convolutional import Conv1D 
from keras.layers.convolutional import MaxPooling1D

Using TensorFlow backend.


In [2]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [3]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 

# choose a number of time steps 
n_steps = 4 

# split into samples 
X, y = split_sequence(raw_seq, n_steps) 

In [4]:
print(X)

[[10 20 30 40]
 [20 30 40 50]
 [30 40 50 60]
 [40 50 60 70]
 [50 60 70 80]]


In [5]:
X.shape

(5, 4)

In [6]:
print(y)

[50 60 70 80 90]


In [7]:
y.shape

(5,)

In [8]:
# reshape from [samples, timesteps] into [samples, subsequences, timesteps, features] 
n_features = 1 
n_seq = 2 
n_steps = 2 
X = X.reshape((X.shape[0], n_seq, n_steps, n_features)) 

In [9]:
print(X)

[[[[10]
   [20]]

  [[30]
   [40]]]


 [[[20]
   [30]]

  [[40]
   [50]]]


 [[[30]
   [40]]

  [[50]
   [60]]]


 [[[40]
   [50]]

  [[60]
   [70]]]


 [[[50]
   [60]]

  [[70]
   [80]]]]


In [10]:
X.shape

(5, 2, 2, 1)

In [11]:
# define model 
model = Sequential() 
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, n_steps, n_features))) 
model.add(TimeDistributed(MaxPooling1D(pool_size=2))) 
model.add(TimeDistributed(Flatten())) 
model.add(LSTM(50, activation='relu')) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=500, verbose=0) 

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [12]:
# demonstrate prediction 
x_input = array([60, 70, 80, 90])

In [13]:
x_input

array([60, 70, 80, 90])

In [14]:
x_input = x_input.reshape((1, n_seq, n_steps, n_features))

In [15]:
x_input

array([[[[60],
         [70]],

        [[80],
         [90]]]])

In [16]:
x_input.shape

(1, 2, 2, 1)

In [17]:
yhat = model.predict(x_input, verbose=0) 

In [18]:
print(yhat)

[[101.7786]]


#### ConvLSTM

In [1]:
# univariate cnn lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import Flatten
from keras.layers import ConvLSTM2D

Using TensorFlow backend.


In [2]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the sequence 
        if end_ix > len(sequence)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [3]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 

# choose a number of time steps 
n_steps = 4 

# split into samples 
X, y = split_sequence(raw_seq, n_steps) 

In [4]:
# reshape from [samples, timesteps] into [samples, timesteps, rows, columns, features] 
n_features = 1 
n_seq = 2 
n_steps = 2 
X = X.reshape((X.shape[0], n_seq, 1, n_steps, n_features)) 

In [5]:
# define model 
model = Sequential() 
model.add(ConvLSTM2D(filters=64, kernel_size=(1,2), activation='relu', input_shape=(n_seq, 1, n_steps, n_features))) 
model.add(Flatten()) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=500, verbose=0) 

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [6]:
# demonstrate prediction 
x_input = array([60, 70, 80, 90]) 
x_input = x_input.reshape((1, n_seq, 1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [7]:
print(yhat)

[[104.02933]]


### Multivariate LSTM Models

#### Multiple Input Series

In [ ]:
# multivariate lstm example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the dataset 
        if end_ix > len(sequences): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1] 
        X.append(seq_x) y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps
n_steps = 3 
# convert into input/output 
X, y = split_sequences(dataset, n_steps) 

In [ ]:
print(X.shape, y.shape)

In [ ]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

In [ ]:
# the dataset knows the number of features, e.g. 3
n_features = X.shape[2] 
# define model 
model = Sequential() 
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features))) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=200, verbose=0) 

In [ ]:
# demonstrate prediction 
x_input = array([[80, 85], [90, 95], [100, 105]]) 
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

####  Multiple Parallel Series

In [ ]:
# multivariate output stacked lstm example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense


In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps 
        # check if we are beyond the dataset 
        if end_ix > len(sequences)-1: 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :] 
        X.append(seq_x) 
        y.append(seq_y)
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps = 3 
# convert into input/output 
X, y = split_sequences(dataset, n_steps) 

In [ ]:
print(X.shape, y.shape)

In [ ]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

In [ ]:
# the dataset knows the number of features, e.g. 3 
n_features = X.shape[2] 
# define model 
model = Sequential() 
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps, n_features))) 
model.add(LSTM(100, activation='relu')) 
model.add(Dense(n_features)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=400, verbose=0)

In [ ]:
# demonstrate prediction 
x_input = array([[70,75,145], [80,85,165], [90,95,185]]) 
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

### Multi-step LSTM Models

#### Data Preparation

In [ ]:
# multi-step data preparation 
from numpy import array

In [ ]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the sequence 
        if out_end_ix > len(sequence): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)


In [ ]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# split into samples 
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out) 

In [ ]:
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

#### Vector Output Model

In [ ]:
# univariate multi-step vector-output stacked lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense

In [ ]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequence)): 
        # find the end of this pattern
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the sequence 
        if out_end_ix > len(sequence): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# split into samples 
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out) 
# reshape from [samples, timesteps] into [samples, timesteps, features] 
n_features = 1 
X = X.reshape((X.shape[0], X.shape[1], n_features)) 

In [ ]:
# define model 
model = Sequential() 
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features))) 
model.add(LSTM(100, activation='relu')) 
model.add(Dense(n_steps_out)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=50, verbose=0) 

In [ ]:
# demonstrate prediction 
x_input = array([70, 80, 90]) 
x_input = x_input.reshape((1, n_steps_in, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

#### Encoder-Decoder Model

In [ ]:
# univariate multi-step encoder-decoder lstm example 
from numpy import array 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense 
from keras.layers import RepeatVector 
from keras.layers import TimeDistributed

In [ ]:
# split a univariate sequence into samples 
def split_sequence(sequence, n_steps_in, n_steps_out): 
    X, y = list(), list() for i in range(len(sequence)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the sequence 
        if out_end_ix > len(sequence): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# split into samples 
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out) 
# reshape from [samples, timesteps] into [samples, timesteps, features] 
n_features = 1 
X = X.reshape((X.shape[0], X.shape[1], n_features)) 
y = y.reshape((y.shape[0], y.shape[1], n_features)) 

In [ ]:
# define model 
model = Sequential() 
model.add(LSTM(100, activation='relu', input_shape=(n_steps_in, n_features))) 
model.add(RepeatVector(n_steps_out)) 
model.add(LSTM(100, activation='relu', return_sequences=True)) 
model.add(TimeDistributed(Dense(1))) 
model.compile(optimizer='adam', loss='mse')
# fit model 
model.fit(X, y, epochs=100, verbose=0) 

In [ ]:
# demonstrate prediction 
x_input = array([70, 80, 90]) 
x_input = x_input.reshape((1, n_steps_in, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

### Multivariate Multi-step LSTM Models

#### Multiple Input Multi-step Output

In [ ]:
# multivariate multi-step stacked lstm example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern 
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out-1 
        # check if we are beyond the dataset 
        if out_end_ix > len(sequences): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix, -1] 
        X.append(seq_x) 
        y.append(seq_y) 
    return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# covert into input/output 
X, y = split_sequences(dataset, n_steps_in, n_steps_out) 

In [ ]:
print(X.shape, y.shape) 
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

In [ ]:
# the dataset knows the number of features, e.g. 2 
n_features = X.shape[2] 
# define model 
model = Sequential() 
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features))) 
model.add(LSTM(100, activation='relu')) 
model.add(Dense(n_steps_out)) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=200, verbose=0) 

In [ ]:
# demonstrate prediction 
x_input = array([[70, 75], [80, 85], [90, 95]]) 
x_input = x_input.reshape((1, n_steps_in, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)

#### Multiple Parallel Input Multi-step Output

In [ ]:
# multivariate multi-step encoder-decoder lstm example 
from numpy import array 
from numpy import hstack 
from keras.models import Sequential 
from keras.layers import LSTM 
from keras.layers import Dense 
from keras.layers import RepeatVector 
from keras.layers import TimeDistributed

In [ ]:
# split a multivariate sequence into samples 
def split_sequences(sequences, n_steps_in, n_steps_out): 
    X, y = list(), list() 
    for i in range(len(sequences)): 
        # find the end of this pattern
        end_ix = i + n_steps_in 
        out_end_ix = end_ix + n_steps_out 
        # check if we are beyond the dataset 
        if out_end_ix > len(sequences): 
            break 
        # gather input and output parts of the pattern 
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :] 
        X.append(seq_x) 
        y.append(seq_y) 
        return array(X), array(y)

In [ ]:
# define input sequence 
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95]) 
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))]) 
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1)) 
in_seq2 = in_seq2.reshape((len(in_seq2), 1)) 
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns 
dataset = hstack((in_seq1, in_seq2, out_seq)) 
# choose a number of time steps 
n_steps_in, n_steps_out = 3, 2 
# covert into input/output 
X, y = split_sequences(dataset, n_steps_in, n_steps_out) 

In [ ]:
print(X.shape, y.shape) 
# summarize the data 
for i in range(len(X)): 
    print(X[i], y[i])

In [ ]:
# the dataset knows the number of features, e.g. 2 
n_features = X.shape[2] 
# define model 
model = Sequential() 
model.add(LSTM(200, activation='relu', input_shape=(n_steps_in, n_features))) 
model.add(RepeatVector(n_steps_out)) 
model.add(LSTM(200, activation='relu', return_sequences=True)) 
model.add(TimeDistributed(Dense(n_features))) 
model.compile(optimizer='adam', loss='mse') 
# fit model 
model.fit(X, y, epochs=300, verbose=0) 

In [ ]:
# demonstrate prediction 
x_input = array([[60, 65, 125], [70, 75, 145], [80, 85, 165]]) 
x_input = x_input.reshape((1, n_steps_in, n_features)) 
yhat = model.predict(x_input, verbose=0) 

In [ ]:
print(yhat)